// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAykvAxplWK_JIlmxt7VnMKriBrMqEdlNc',
    appId: '1:165312428480:web:624766f5acb5322a8d7025',
    messagingSenderId: '165312428480',
    projectId: 'mobile-dayat',
    authDomain: 'mobile-dayat.firebaseapp.com',
    databaseURL: 'https://mobile-dayat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-dayat.appspot.com',
    measurementId: 'G-F8QGYMXKSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO2zUKk9DoEWk1C9-n0srzIUr-94_1O-k',
    appId: '1:165312428480:android:6d0fe9e568c7c7648d7025',
    messagingSenderId: '165312428480',
    projectId: 'mobile-dayat',
    databaseURL: 'https://mobile-dayat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-dayat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH0coS1FT9vFhIVlbteQ6tMf4QcEuwSFo',
    appId: '1:165312428480:ios:57bae48d0d20d5508d7025',
    messagingSenderId: '165312428480',
    projectId: 'mobile-dayat',
    databaseURL: 'https://mobile-dayat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-dayat.appspot.com',
    iosBundleId: 'com.example.mobileDua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH0coS1FT9vFhIVlbteQ6tMf4QcEuwSFo',
    appId: '1:165312428480:ios:57bae48d0d20d5508d7025',
    messagingSenderId: '165312428480',
    projectId: 'mobile-dayat',
    databaseURL: 'https://mobile-dayat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-dayat.appspot.com',
    iosBundleId: 'com.example.mobileDua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAykvAxplWK_JIlmxt7VnMKriBrMqEdlNc',
    appId: '1:165312428480:web:3a83e65b936586728d7025',
    messagingSenderId: '165312428480',
    projectId: 'mobile-dayat',
    authDomain: 'mobile-dayat.firebaseapp.com',
    databaseURL: 'https://mobile-dayat-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-dayat.appspot.com',
    measurementId: 'G-GZTPYEL4J5',
  );
}
